plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace = "com.vlad1m1r.lemniscate.sample"
    compileSdk = 37
    compileSdkMinor = 1

    defaultConfig {
        applicationId = "com.vlad1m1r.lemniscate.sample"
        minSdk = 23
        targetSdk = 37
        versionCode = 145
        versionName = "1.4.5"
    }
    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.circleindicator

    implementation project(':lemniscate')
}
